
services:
  - type: worker
    name: binance-signal-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
      - key: CHAT_ID
        value: your_telegram_chat_id_here
